# Generated by Django 5.1.6 on 2025-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
