# Generated by Django 5.1.6 on 2025-02-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
