# Generated by Django 5.1.6 on 2025-02-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
